### ISSUE TITLE
OpenCover from VS2015 output renders unhandled InvalidCastException

### ISSUE THREAD

**Issue by xJom** [danielpalme/ReportGenerator#30]
Generating an codecoveragereport.xml with the command:
```
"C:\Users\<my_user>\AppData\Local\Apps\OpenCover\OpenCover.Console.exe" -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"/Logger:trx /inIsolation /Platform:x64 bin/Release/Model.Tests.dll" -filter:"+[*]*" -mergebyhash -output:"codecoveragereport.xml"
```
And trying to generate a report on the output with
```
ReportGenerator.exe -reports:codecoveragereport.xml -targetDir:TTS2_Code_Coverage_Report
```
Gives the following error:
```
08:48:30 Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'ICSharpCode.NRefactory.CSharp.ReturnStatement' to type 'ICSharpCode.NRefactory.CSharp.BlockStatement'.
08:48:30    at ICSharpCode.NRefactory.CSharp.CSharpParser.ConversionVisitor.Visit(Property p)
08:48:30    at Mono.CSharp.StructuralVisitor.VisitTypeDefinition(TypeDefinition tc)
08:48:30    at ICSharpCode.NRefactory.CSharp.CSharpParser.ConversionVisitor.Visit(Class c)
08:48:30    at ICSharpCode.NRefactory.CSharp.CSharpParser.ConversionVisitor.Visit(NamespaceContainer ns)
08:48:30    at ICSharpCode.NRefactory.CSharp.CSharpParser.ConversionVisitor.Visit(ModuleContainer mc)
08:48:30    at ICSharpCode.NRefactory.CSharp.CSharpParser.Parse(CompilerCompilationUnit top, String fileName)
08:48:30    at ICSharpCode.NRefactory.CSharp.CSharpParser.Parse(ITextSource program, String fileName, Int32 initialLine, Int32 initialColumn)
08:48:30    at ICSharpCode.NRefactory.CSharp.CSharpParser.Parse(ITextSource program, String fileName)
08:48:30    at Palmmedia.ReportGenerator.Parser.Preprocessing.CodeAnalysis.SourceCodeAnalyzer.GetParentNode(String filename)
08:48:30    at Palmmedia.ReportGenerator.Parser.Preprocessing.CodeAnalysis.SourceCodeAnalyzer.FindSourceElement(String filename, SourceElement sourceElement)
08:48:30    at Palmmedia.ReportGenerator.Parser.Preprocessing.ReportPreprocessorBase.<>c__DisplayClass13_0.<SearchElement>b__0()
08:48:30    at Palmmedia.ReportGenerator.Parser.Preprocessing.ReportPreprocessorBase.SearchElement(SourceElement sourceElement, Dictionary`2 filenameByFileIdDictionary, IEnumerable`1 fileIdsOfClass, XContainer reportElement, Action`3 updateReportElement, XContainer filesContainer)
08:48:30    at Palmmedia.ReportGenerator.Parser.Preprocessing.OpenCoverReportPreprocessor.AddCoverageDataOfAutoProperties(XElement module)
08:48:30    at Palmmedia.ReportGenerator.Parser.Preprocessing.OpenCoverReportPreprocessor.Execute()
08:48:30    at Palmmedia.ReportGenerator.Parser.ParserFactory.GetParsersOfFile(String reportFile, ClassSearcherFactory classSearcherFactory, ClassSearcher globalClassSearcher)
08:48:30    at Palmmedia.ReportGenerator.Parser.ParserFactory.CreateParser(IEnumerable`1 reportFiles, IEnumerable`1 sourceDirectories)
08:48:30    at Palmmedia.ReportGenerator.Program.Execute(ReportConfiguration configuration)
08:48:30    at Palmmedia.ReportGenerator.Program.Main(String[] args)
```
This might as well be an error in the NRefactory code, so maybe I should post there as well?

**Comment by danielpalme** [comment]
Thanks for reporting this. Please don't create an issue for NRefactory, i look into my code first

**Comment by xJom** [comment]
I accidentally removed the xml-file, and will re-generate it soon.
We have two new features in VS2015 which we are guessing might be the culprits:
```
public string Name => "Robin"; (expression body)
```
and
```
MyEvent?.Invoke(this, args); (null propagation)
```
Especially the first, since the actual return-statement which was used in VS2013 is not needed any longer. But it is just a guess right now.

I did check into the commits since 5.5.1 release of NRefactory, but I didn't find anything pointing in these directions...

**Comment by MoJo2600** [comment]
I experience the same issue. The problem is, that C# 6.0 is not supported by the NRefactory Version you're using. I tried to upgrade your code to the latest NRefactory version, but had no success.

**Comment by danielpalme** [comment]
Could you please try again with new version 2.3.3.0:
https://www.nuget.org/packages/ReportGenerator/2.3.3

**Comment by MoJo2600** [comment]
I can confirm, that 2.3.3.0 fixed this issue for me. Thanks for your great work!

**Comment by xJom** [comment]
Confirmed for me also. Kudos!
