### ISSUE TITLE
Using ReportGenerator in MSBuild is broken with dotnet core sdk 3.1.200

### ISSUE THREAD

**Issue by jon-armen** [danielpalme/ReportGenerator#335]
Using global.json to control the specific sdk being used, when the sdk is 3.1.100, the report is created normally.  When sdk is 3.2.100, the report fails to create with the following stacktrace:

```
2020-03-27T06:45:54: Sequence contains no elements
2020-03-27T06:45:54:    at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Palmmedia.ReportGenerator.Core.Plugin.ReflectionPluginLoader.CreateAssemblyLoader() in C:\Users\jarmen\Downloads\ReportGenerator-master\ReportGenerator-master\src\ReportGenerator.Core\Plugin\ReflectionPluginLoader.cs:line 118
   at Palmmedia.ReportGenerator.Core.Plugin.ReflectionPluginLoader..ctor(IReadOnlyCollection`1 plugins) in C:\Users\jarmen\Downloads\ReportGenerator-master\ReportGenerator-master\src\ReportGenerator.Core\Plugin\ReflectionPluginLoader.cs:line 39
   at Palmmedia.ReportGenerator.Core.Generator.GenerateReport(IReportConfiguration reportConfiguration, Settings settings, RiskHotspotsAnalysisThresholds riskHotspotsAnalysisThresholds) in C:\Users\jarmen\Downloads\ReportGenerator-master\ReportGenerator-master\src\ReportGenerator.Core\Generator.cs:line 100
```

For some reason, in ReflectionPluginLoader.CreateAssemblyLoader typeof(IAssemblyLoader).IsAssignableFrom(t) returns false.  Generator is being run using ReportGenerator msbuild task

**Comment by danielpalme** [comment]
Thanks for reporting this issue. Will have look at the problem.

**Comment by danielpalme** [comment]
I was able to reproduce your issue.

I opened an issue here: https://github.com/dotnet/sdk/issues/11043

**Comment by danielpalme** [comment]
In release 4.5.3 I introduced a workaround to this problem.
The release should be available in a few minutes.

Could you please give it a try?

**Comment by jon-armen** [comment]
All good!  Thank you for the quick fix (work around).
