### ISSUE TITLE
5.1.8 breaks generation of report when including historic reports

### ISSUE THREAD

**Issue by jon-armen** [danielpalme/ReportGenerator#522]
**Describe the bug**
As of 5.1.7, this was working correctly.  5.1.8 breaks.

Tool 'dotnet-reportgenerator-globaltool' (version '5.1.8') was successfully installed. Entry is added to the manifest file /home/vsts/work/1/s/.config/dotnet-tools.json.
2022-05-18T15:22:48: Arguments
2022-05-18T15:22:48:  -reports:/home/vsts/work/1/s/coverage/repo/Chrome */lcov.info
2022-05-18T15:22:48:  -targetdir:/home/vsts/work/1/s/coverage-report
2022-05-18T15:22:48:  -historydir:/home/vsts/work/1/s/coverage-report-history
2022-05-18T15:22:48:  -reporttypes:HtmlInline_AzurePipelines;Cobertura;Badges
2022-05-18T15:22:48:  -tag:20220518.8
2022-05-18T15:22:48: Reading historic reports
2022-05-18T15:22:48: An item with the same key has already been added. Key: Default+form-input-component.ts
2022-05-18T15:22:48:    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Palmmedia.ReportGenerator.Core.Reporting.History.HistoryParser.ApplyHistoricCoverage(IEnumerable`1 assemblies, List`1 overallHistoricCoverages) in /_/src/ReportGenerator.Core/Reporting/History/HistoryParser.cs:line 89
   at Palmmedia.ReportGenerator.Core.Generator.GenerateReport(IReportConfiguration reportConfiguration, Settings settings, RiskHotspotsAnalysisThresholds riskHotspotsAnalysisThresholds, ParserResult parserResult) in /_/src/ReportGenerator.Core/Generator.cs:line 242
   at Palmmedia.ReportGenerator.Core.Generator.GenerateReport(IReportConfiguration reportConfiguration, Settings settings, RiskHotspotsAnalysisThresholds riskHotspotsAnalysisThresholds) in /_/src/ReportGenerator.Core/Generator.cs:line 139

**Comment by danielpalme** [comment]
Thanks for reporting this problem.
Version 5.1.9 will fix this (will be available in a few minutes).
