### ISSUE TITLE
Empty file paths in OpenCover snapshot causes failure

### ISSUE THREAD

**Issue by gregbty** [danielpalme/ReportGenerator#97]
The generator seems to be failing when attempting to process an empty file path that occurs in an OpenCover coverage snapshot:

```xml
<File uid="18" fullPath="" />
```

It produces the following error: `System.ArgumentException: Empty path name is not legal.`

**Comment by danielpalme** [comment]
I will have a look at this.
Do you have an idea how this can happen? Every file should have a corresponding path...

**Comment by gregbty** [comment]
I just submitted an issue with OpenCover. It may be related to some of the pre and post processing actions I am doing when building. Here is the full stack trace of the issue when running ReportGenerator:

```
Unhandled Exception: System.ArgumentException: Empty path name is not legal.
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Palmmedia.ReportGenerator.Parser.Preprocessing.CodeAnalysis.SourceCodeAnalyzer.GetParentNode(String filename)
   at Palmmedia.ReportGenerator.Parser.Preprocessing.CodeAnalysis.SourceCodeAnalyzer.FindSourceElement(String filename, SourceElement sourceElement)
   at Palmmedia.ReportGenerator.Parser.Preprocessing.ReportPreprocessorBase.<>c__DisplayClass13_0.<SearchElement>b__0()
   at Palmmedia.ReportGenerator.Parser.Preprocessing.ReportPreprocessorBase.SearchElement(SourceElement sourceElement, Dictionary`2 filenameByFileIdDictionary, IEnumerable`1 fileIdsOfClass, XContainer reportElement, Action`3 updateReportElement, XContainer filesContainer)
   at Palmmedia.ReportGenerator.Parser.Preprocessing.OpenCoverReportPreprocessor.AddCoverageDataOfAutoProperties(XElement module)
   at Palmmedia.ReportGenerator.Parser.Preprocessing.OpenCoverReportPreprocessor.Execute()
   at Palmmedia.ReportGenerator.Parser.ParserFactory.GetParsersOfFile(String reportFile, ClassSearcherFactory classSearcherFactory, ClassSearcher globalClassSearcher)
   at Palmmedia.ReportGenerator.Parser.ParserFactory.CreateParser(IEnumerable`1 reportFiles, IEnumerable`1 sourceDirectories)
   at Palmmedia.ReportGenerator.Generator.GenerateReport(ReportConfiguration reportConfiguration)
   at Palmmedia.ReportGenerator.Program.Main(String[] args)
```
